package com.antoiovi.project1.model;
// Generated 15-gen-2019 14.58.19 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

/**
 * Persone generated by hbm2java
 */
@Entity
@Table(name = "persone", catalog = "antoiovi_tutorials", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
@NamedQueries(@NamedQuery(name = "allPersons", query = "SELECT * from Persone"))
public class Persone implements java.io.Serializable {

	private Integer personaId;
	private String username;
	private String nome;
	private String cognome;
	private String email;
	private String password;

	public Persone() {
	}

	public Persone(String username, String nome, String cognome) {
		this.username = username;
		this.nome = nome;
		this.cognome = cognome;
	}
	public Persone(String username, String nome, String cognome, String email,
			String password) {
		this.username = username;
		this.nome = nome;
		this.cognome = cognome;
		this.email = email;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "persona_id", unique = true, nullable = false)
	public Integer getPersonaId() {
		return this.personaId;
	}

	public void setPersonaId(Integer personaId) {
		this.personaId = personaId;
	}

	@Column(name = "username", unique = true, nullable = false, length = 10)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "nome", nullable = false, length = 10)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cognome", nullable = false, length = 10)
	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	@Column(name = "email", length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 256)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
